version: "3"

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    image: ghcr.io/yey007/pingmc:latest
    env_file:
      - bot.env
      - db.env
    depends_on:
      - db
  db:
    image: library/postgres:alpine
    env_file:
      - db.env